import type { Metadata } from "next";
import { SpeedInsights } from "@vercel/speed-insights/next";
// 1. Import the fonts from Google
import { Space_Grotesk, Outfit } from "next/font/google"; 
import "./globals.css";
import { ThemeProvider } from "@/components/providers"; 
import { GlobalFeedback } from "../components/feedback/global-feedback";

// 2. Configure Space Grotesk
const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space", // This defines the CSS variable name
  display: "swap",
});

// 3. Configure Outfit
const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit", // This defines the CSS variable name
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        // 4. Inject the font variables into the body className
        className={`${outfit.variable} ${spaceGrotesk.variable} antialiased bg-white dark:bg-black selection:bg-[#B02E2B] selection:text-white font-sans`}
      >
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem={false}>
          {children}
          <GlobalFeedback />
        </ThemeProvider>
        <SpeedInsights />
      </body>
    </html>
  );
}